import assert from "node:assert/strict";
import test from "node:test";
import { createFakeLlmProvider } from "@/lib/llm/providers/fake";
import { inspectApplicationForm } from "@/core/applications/formInspection";
import { approveDraft, beginSubmission, draftApplication, editAnswer } from "@/core/applications/workflow";
import { matchQuestionBank } from "@/core/applications/questionBank";
import { trackOpportunities } from "@/core/applications/tracker";
import { createApprovedFillPlan } from "@/server/applications/submission";
import type { ApplicationDraft, QuestionBankEntry } from "@/core/applications/types";

const bank: QuestionBankEntry[] = [{ id: "bio", canonicalQuestion: "Tell us about yourself", answer: "Builder and student.", aliases: ["Introduce yourself", "Short bio"], tags: [], updatedAt: "2026-01-01" }];
const base = (): ApplicationDraft => ({ id: "a", opportunityId: "o", applicationUrl: "https://example.test/apply", status: "drafting", draftVersion: 1, approvedAt: null, approvedDraftVersion: null, questions: [{ id: "name", label: "Name", fieldType: "text", required: true, options: [], selector: "#name", answer: null, answerSource: "unresolved", needsUserInput: false }, { id: "bio", label: "Introduce yourself", fieldType: "textarea", required: true, options: [], selector: "#bio", answer: null, answerSource: "unresolved", needsUserInput: false }, { id: "why", label: "Why this event?", fieldType: "textarea", required: true, options: [], selector: "#why", answer: null, answerSource: "unresolved", needsUserInput: false }, { id: "attend", label: "Can you attend October 5–7?", fieldType: "radio", required: true, options: ["Yes", "No"], selector: "#attend", answer: null, answerSource: "unresolved", needsUserInput: false }] });
test("resolves profile and bank, batches AI, then preserves unresolved input", async () => { let calls = 0; const llm = createFakeLlmProvider({ handler: () => { calls++; return JSON.stringify({ answers: [{ id: "why", answer: "Relevant to my work." }] }); } }); const result = await draftApplication(base(), { name: "Ada" }, bank, llm); assert.equal(calls, 1); assert.equal(result.draft.status, "needs_input"); assert.equal(result.draft.questions[0].answerSource, "profile"); assert.equal(result.draft.questions[1].answerSource, "question_bank"); assert.equal(result.draft.questions[2].answerSource, "ai"); assert.equal(result.metrics.user, 1); });
test("approval is explicit and edits invalidate it", () => { const ready = { ...base(), status: "ready_for_review" as const, questions: base().questions.map((q) => ({ ...q, answer: "x" })) }; assert.throws(() => beginSubmission(ready)); const approved = approveDraft(ready); assert.equal(beginSubmission(approved).status, "submitting"); assert.throws(() => beginSubmission(editAnswer(approved, "why", "changed"))); });
test("the final required user answer returns a draft to review without another model call", () => { const draft = { ...base(), status: "needs_input" as const, questions: base().questions.map((q) => q.id === "attend" ? q : { ...q, answer: "x" }) }; const updated = editAnswer(draft, "attend", "Yes"); assert.equal(updated.status, "ready_for_review"); assert.equal(updated.questions.find((q) => q.id === "attend")?.answerSource, "user"); });
test("safe fill plans require the exact approved draft", () => { const ready = { ...base(), status: "ready_for_review" as const, questions: base().questions.map((q) => ({ ...q, answer: "x" })) }; assert.throws(() => createApprovedFillPlan(ready)); assert.equal(createApprovedFillPlan(approveDraft(ready)).length, 4); });
test("question matching, inspection, and tracker are deterministic", () => { assert.equal(matchQuestionBank("Short bio", bank)?.id, "bio"); assert.equal(matchQuestionBank("What is your tax number?", bank), null); assert.equal(inspectApplicationForm('<label for="x">Bio</label><textarea id="x" required maxlength="500"></textarea>')[0]?.maxLength, 500); assert.deepEqual(trackOpportunities([{ id: "o", title: "Open", applicationOpensAt: "2026-01-01", applicationDeadline: "2026-01-02" }], new Date("2026-01-01T12:00:00Z")), [{ type: "APPLICATION_OPEN", opportunityId: "o" }, { type: "DEADLINE_SOON", opportunityId: "o" }]); });
