import { randomUUID } from "node:crypto";
import path from "node:path";
import { loadLocalEnv } from "@/cli/loadEnv";
loadLocalEnv();
async function main(): Promise<void> {
  const { createServiceSupabaseClient } = await import("@/lib/supabase/createServiceClient"); const { createApplication, getApplication, saveDraft } = await import("@/server/applications/repository"); const { sendDiscord } = await import("@/server/notifications/service");
  const db = createServiceSupabaseClient(); const fixtureId = randomUUID(); const fingerprint = `pass2-discord-ready-submit-fixture-${fixtureId}`; const fixtureUrl = "http://127.0.0.1:3000/fixtures/controlled-application";
  let candidateId = (await db.from("candidates").select("id").eq("fingerprint", fingerprint).maybeSingle()).data?.id;
  if (!candidateId) { const inserted = await db.from("candidates").insert({ name: "Pass 2 Discord Submit Fixture", source: "pass2_fixture", fingerprint, score: 0, apply_url: fixtureUrl, themes: [], why_match: [], red_flags: [], status: "APPROVED" }).select("id").single(); if (inserted.error) throw inserted.error; candidateId = inserted.data.id; }
  const existing = await db.from("applications").select("id").eq("candidate_id", candidateId).maybeSingle(); const resume = path.resolve("scripts/fixtures/resume.pdf"); const questions = [{ id: randomUUID(), label: "Name", fieldType: "text", required: true, options: [], selector: "#name", answer: "Ada Lovelace", answerSource: "user" as const, needsUserInput: false }, { id: randomUUID(), label: "Can you attend all days?", fieldType: "radio", required: true, options: ["Yes", "No"], selector: "input[name=\"attendance\"]", answer: "Yes", answerSource: "user" as const, needsUserInput: false }, { id: randomUUID(), label: "I consent to the code of conduct", fieldType: "checkbox", required: true, options: ["Yes"], selector: "#consent", answer: "Yes", answerSource: "user" as const, needsUserInput: false }, { id: randomUUID(), label: "Short bio", fieldType: "textarea", required: true, options: [], selector: "#bio", answer: "Student builder.", answerSource: "user" as const, needsUserInput: false }, { id: randomUUID(), label: "GitHub profile", fieldType: "url", required: true, options: [], selector: "#github", answer: "https://github.com/ada", answerSource: "user" as const, needsUserInput: false }, { id: randomUUID(), label: "Upload your resume", fieldType: "file", required: true, options: [], selector: "#resume", answer: resume, answerSource: "asset_bank" as const, needsUserInput: false }, { id: randomUUID(), label: "Can you arrange travel?", fieldType: "select", required: true, options: ["Yes", "No"], selector: "#travel", answer: "Yes", answerSource: "user" as const, needsUserInput: false }];
  let application = existing.data ? await getApplication(existing.data.id) : await createApplication(candidateId, fixtureUrl, questions, { fixture: true, fixtureId }); if (!application) throw new Error("Could not create ready fixture."); application = await saveDraft({ ...application, status: "ready_to_submit", currentPage: 4, totalPages: 4, checkpoint: { fixture: true, fixtureId } }); await sendDiscord({ type: "APPLICATION_READY_TO_SUBMIT", priority: 2, opportunityId: candidateId, applicationId: application.id, title: "Pass 2 fixture is ready to submit", body: "Controlled local form only. Submit now is safe for this fixture.", actionUrl: `/drafts/${application.id}` }); console.log(JSON.stringify({ applicationId: application.id, fixtureUrl }));
}
void main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exit(1); });
