"use client";
import { useCallback, useEffect, useState } from "react";
import type { ApplicationDraft } from "@/core/applications/types";
export function ApplicationEditor({ id }: { id: string }) {
  const [application, setApplication] = useState<ApplicationDraft | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/applications/${id}`); const body = await response.json() as { data?: { application?: ApplicationDraft } }; setApplication(body.data?.application ?? null); }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function action(body: Record<string, string>) { const response = await fetch(`/api/applications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { data?: { application?: ApplicationDraft; message?: string }; error?: { message?: string } }; setMessage(payload.data?.message ?? payload.error?.message ?? (response.ok ? "Saved." : "Could not save.")); if (payload.data?.application) setApplication(payload.data.application); }
  if (!application) return <p aria-busy="true" className="text-muted">Loading application…</p>;
  const blockers = application.questions.filter((question) => question.required && !question.answer);
  return <div className="space-y-4"><div className="hf-sheet-frame flex flex-wrap items-center justify-between gap-3 p-4"><div><span className="font-mono text-sm">{application.status.replaceAll("_", " ")}</span><p className="mt-1 text-xs text-muted">{application.currentPage ? `External form page ${application.currentPage}${application.totalPages ? `/${application.totalPages}` : ""}` : "Form checkpoint saved"} · Draft v{application.draftVersion}</p></div><a className="hf-focus text-sm underline" href={application.applicationUrl} target="_blank" rel="noreferrer">Open form</a></div>{blockers.length ? <div className="border border-accent-warn bg-inset p-3 text-sm"><strong>{blockers.length} blocker{blockers.length === 1 ? "" : "s"}</strong><p className="mt-1 text-muted">Complete the required fields, then choose Save & Continue. It will never submit the external application.</p></div> : null}{application.questions.map((question) => <div className="hf-sheet-frame p-4" key={question.id}><div className="flex items-start justify-between gap-3"><label className="font-medium" htmlFor={question.id}>{question.label}{question.required ? " *" : " (optional)"}</label><span className="font-mono text-xs text-muted">{question.answerSource.replaceAll("_", " ")}</span></div><textarea id={question.id} className="hf-focus mt-3 min-h-24 w-full border border-border bg-inset px-3 py-2" defaultValue={question.answer ?? ""} onBlur={(event) => { if (event.target.value !== (question.answer ?? "")) void action({ action: "edit", questionId: question.id, answer: event.target.value }); }} /><p className="mt-2 text-xs text-muted">{question.needsUserInput ? "Required blocker — your answer is needed" : "Editable; this answer can always be changed."}</p></div>)}<div className="sticky bottom-0 flex flex-wrap gap-2 border border-border bg-surface p-3"><button className="hf-focus border border-accent-save px-4 py-2 text-sm" onClick={() => void action({ action: "save" })}>Save</button><button className="hf-focus border border-accent-approve px-4 py-2 text-sm" onClick={() => void action({ action: "save_continue" })} disabled={application.status === "user_managed"}>Save &amp; Continue</button><button className="hf-focus border border-border px-4 py-2 text-sm" onClick={() => void action({ action: "pause" })}>Pause</button><button className="hf-focus border border-accent-warn px-4 py-2 text-sm" onClick={() => void action({ action: "do_myself" })}>Do this myself</button><button className="hf-focus border border-red-700 px-4 py-2 text-sm" onClick={() => { if (window.confirm("Delete this draft? This cannot be undone.")) void action({ action: "delete" }); }}>Delete draft</button></div><p role="status" className="text-sm text-muted">{message}</p></div>;
}
