"use client";
import { useCallback, useEffect, useState } from "react";
import type { ApplicationDraft } from "@/core/applications/types";
export function ApplicationEditor({ id }: { id: string }) {
  const [application, setApplication] = useState<ApplicationDraft | null>(null); const [message, setMessage] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/applications/${id}`); const body = await response.json() as { data?: { application?: ApplicationDraft } }; setApplication(body.data?.application ?? null); }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function action(body: Record<string, string>) { const response = await fetch(`/api/applications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { data?: { application?: ApplicationDraft; message?: string }; error?: { message?: string } }; setMessage(payload.data?.message ?? payload.error?.message ?? (response.ok ? "Saved." : "Could not save.")); if (payload.data?.application) setApplication(payload.data.application); }
  if (!application) return <p aria-busy="true" className="text-muted">Loading application…</p>;
  return <div className="space-y-4"><div className="hf-sheet-frame flex flex-wrap items-center justify-between gap-3 p-4"><span className="font-mono text-sm">{application.status.replaceAll("_", " ")}</span><a className="hf-focus text-sm underline" href={application.applicationUrl} target="_blank" rel="noreferrer">Open form</a></div>{application.questions.map((question) => <div className="hf-sheet-frame p-4" key={question.id}><div className="flex items-start justify-between gap-3"><label className="font-medium" htmlFor={question.id}>{question.label}{question.required ? " *" : ""}</label><span className="font-mono text-xs text-muted">{question.answerSource.replaceAll("_", " ")}</span></div><textarea id={question.id} className="hf-focus mt-3 min-h-24 w-full border border-border bg-inset px-3 py-2" defaultValue={question.answer ?? ""} onBlur={(event) => { if (event.target.value !== (question.answer ?? "")) void action({ action: "edit", questionId: question.id, answer: event.target.value }); }} /><p className="mt-2 text-xs text-muted">{question.needsUserInput ? "Needs your input" : "Editable before approval"}</p></div>)}<button className="hf-focus border border-accent-approve px-4 py-2" disabled={application.status !== "ready_for_review"} onClick={() => void action({ action: "approve" })}>Approve for submission</button><p role="status" className="text-sm text-muted">{message}</p></div>;
}
