"use client";
import { useEffect, useState } from "react";
import type { AssetBankEntry } from "@/core/applications/types";
export function AssetBankEditor() {
  const [assets, setAssets] = useState<AssetBankEntry[]>([]); const [message, setMessage] = useState(""); const [label, setLabel] = useState(""); const [kind, setKind] = useState<"file" | "link">("link"); const [assetType, setAssetType] = useState(""); const [value, setValue] = useState(""); const [filename, setFilename] = useState("");
  const load = async () => { const response = await fetch("/api/asset-bank"); const body = await response.json() as { data?: { assets?: AssetBankEntry[] } }; setAssets(body.data?.assets ?? []); };
  useEffect(() => { void load(); }, []);
  async function save() { const response = await fetch("/api/asset-bank", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, kind, assetType, value, filename: filename || null, isDefault: false }) }); if (!response.ok) { setMessage("Could not save asset."); return; } setLabel(""); setAssetType(""); setValue(""); setFilename(""); setMessage("Asset saved."); await load(); }
  return <div className="space-y-4"><form className="hf-sheet-frame grid gap-3 p-4" onSubmit={(e) => { e.preventDefault(); void save(); }}><label className="text-sm">Label<input required className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Resume 2026" /></label><label className="text-sm">Kind<select className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={kind} onChange={(e) => setKind(e.target.value as "file" | "link")}><option value="link">Link</option><option value="file">File reference</option></select></label><label className="text-sm">Type<input required className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={assetType} onChange={(e) => setAssetType(e.target.value)} placeholder="resume, github, portfolio" /></label><label className="text-sm">{kind === "file" ? "Stored file reference" : "URL"}<input required className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={value} onChange={(e) => setValue(e.target.value)} /></label>{kind === "file" ? <label className="text-sm">Filename<input className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={filename} onChange={(e) => setFilename(e.target.value)} /></label> : null}<button className="hf-focus w-fit border border-accent-save px-4 py-2 text-sm">Save asset</button></form><ul className="space-y-2">{assets.map((asset) => <li className="hf-sheet-frame p-3" key={asset.id}><strong>{asset.label}</strong><p className="text-sm text-muted">{asset.kind} · {asset.assetType} · updated {new Date(asset.updatedAt).toLocaleDateString()}</p></li>)}</ul><p role="status" className="text-sm text-muted">{message}</p></div>;
}
