"use client";
import { useRef, useState } from "react";
import type { AssetBankEntry } from "@/core/applications/types";

export function AssetBankEditor({ initialAssets }: { initialAssets: AssetBankEntry[] }) {
  const [assets, setAssets] = useState(initialAssets); const [label, setLabel] = useState(""); const [assetType, setAssetType] = useState("resume"); const [link, setLink] = useState(""); const [kind, setKind] = useState<"file" | "link">("file"); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [uploading, setUploading] = useState(false); const picker = useRef<HTMLInputElement>(null);
  async function reload() { const response = await fetch("/api/asset-bank"); const body = await response.json() as { data?: { assets?: AssetBankEntry[] } }; setAssets(body.data?.assets ?? []); }
  async function save() { setUploading(true); setMessage(""); try { if (kind === "file") { if (!file) { setMessage("Choose a file first."); return; } const form = new FormData(); form.set("label", label || file.name); form.set("assetType", assetType); form.set("file", file); const response = await fetch("/api/asset-bank", { method: "PUT", body: form }); if (!response.ok) throw new Error((await response.json() as { error?: { message?: string } }).error?.message ?? "Upload failed."); } else { const response = await fetch("/api/asset-bank", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ label, kind, assetType, value: link, filename: null, isDefault: false }) }); if (!response.ok) throw new Error("Could not save link."); } setLabel(""); setLink(""); setFile(null); if (picker.current) picker.current.value = ""; setMessage(kind === "file" ? "File uploaded to the Asset Bank." : "Link saved."); await reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not save asset."); } finally { setUploading(false); } }
  async function remove(asset: AssetBankEntry) { if (!window.confirm(`Delete ${asset.label}?`)) return; const response = await fetch(`/api/asset-bank?id=${asset.id}`, { method: "DELETE" }); setMessage(response.ok ? "Asset deleted." : "Could not delete asset."); if (response.ok) await reload(); }
  return <div className="space-y-6"><form className="hf-sheet-frame space-y-4 p-5" onSubmit={(event) => { event.preventDefault(); void save(); }}><div className="flex flex-wrap gap-2" role="group" aria-label="Asset type"><button type="button" className={`hf-btn ${kind === "file" ? "hf-btn-primary" : "hf-btn-ghost"}`} onClick={() => setKind("file")}>Upload a file</button><button type="button" className={`hf-btn ${kind === "link" ? "hf-btn-primary" : "hf-btn-ghost"}`} onClick={() => setKind("link")}>Save a link</button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">Label<input required className="hf-input mt-1" value={label} onChange={(event) => setLabel(event.target.value)} placeholder={kind === "file" ? "Resume" : "GitHub"} /></label><label className="text-sm">Type<input required className="hf-input mt-1" value={assetType} onChange={(event) => setAssetType(event.target.value)} placeholder="resume, github, portfolio" /></label></div>{kind === "file" ? <label className="block cursor-pointer border border-dashed border-border p-6 text-center transition-colors hover:border-accent-save"><input ref={picker} className="sr-only" type="file" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><span className="block font-medium">Drop a file here or Browse</span><span className="mt-1 block text-sm text-muted">PDFs, documents, decks, and images up to 12 MB</span>{file ? <span className="mt-3 block text-sm text-foreground">{file.name} · {Math.ceil(file.size / 1024)} KB</span> : null}</label> : <label className="text-sm">Reusable URL<input required type="url" className="hf-input mt-1" value={link} onChange={(event) => setLink(event.target.value)} placeholder="https://github.com/you" /></label>}<button disabled={uploading} className="hf-btn hf-btn-primary" type="submit">{uploading ? "Uploading…" : kind === "file" ? "Upload asset" : "Save link"}</button></form><ul className="divide-y divide-border border-y border-border" aria-label="Saved assets">{assets.map((asset) => <li className="flex flex-wrap items-center justify-between gap-3 py-4" key={asset.id}><div><p className="font-medium">{asset.label}</p><p className="mt-1 text-sm text-muted">{asset.kind === "file" ? `${asset.filename ?? asset.label} · Updated ${new Date(asset.updatedAt).toLocaleDateString()}` : asset.value}</p></div><div className="flex gap-2">{asset.kind === "file" ? <a className="hf-btn hf-btn-ghost" href={`/api/asset-bank/file?id=${asset.id}`} target="_blank" rel="noreferrer">View / download</a> : <a className="hf-btn hf-btn-ghost" href={asset.value} target="_blank" rel="noreferrer">Open</a>}<button className="hf-btn hf-btn-ghost" type="button" onClick={() => void remove(asset)}>Delete</button></div></li>)}</ul><p role="status" className="text-sm text-muted">{message}</p></div>;
}
