"use client";
import { useState } from "react";
const defaultFields = ["name", "email", "phone", "school", "program", "graduationYear", "cityCountry", "github", "linkedin", "portfolio", "bio"];
export function ProfileEditor({ initialFields }: { initialFields: Record<string, string> }) {
  const [fields, setFields] = useState(initialFields); const [message, setMessage] = useState(""); const [editing, setEditing] = useState(false);
  const names = [...new Set([...defaultFields, ...Object.keys(fields)])];
  async function save() { setMessage("Saving…"); const response = await fetch("/api/profile", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ fields }) }); setMessage(response.ok ? "Profile saved." : "Could not save profile."); }
  const groups = [["Personal", ["name", "email", "phone", "cityCountry"]], ["Education", ["school", "program", "graduationYear"]], ["Links", ["github", "linkedin", "portfolio"]]] as const;
  const label = (name: string) => name.replace(/([A-Z])/g, " $1").replace(/^./, (letter) => letter.toUpperCase());
  return <form className="hf-sheet-frame space-y-6 p-5 sm:p-7" onSubmit={(event) => { event.preventDefault(); void save(); setEditing(false); }}><div className="flex items-start justify-between gap-4 border-b border-border pb-5"><div className="flex gap-3"><div className="flex h-12 w-12 items-center justify-center border border-border font-medium">{(fields.name || "?").slice(0, 1).toUpperCase()}</div><div><h2 className="font-medium">{fields.name || "Your profile"}</h2><p className="text-sm text-muted">{fields.email || "Add your contact details"}</p></div></div><button type="button" className="hf-btn hf-btn-ghost" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Edit"}</button></div><p className="text-sm text-muted">Factual data only—this is never sent to a model just to populate matching fields.</p>{groups.map(([heading, keys]) => <section key={heading}><h3 className="hf-section-label mb-3">{heading}</h3><div className="grid gap-4 sm:grid-cols-2">{keys.map((name) => <label key={name} className="text-sm"><span className="mb-1 block text-muted">{label(name)}</span>{editing ? <input className="hf-input" value={fields[name] ?? ""} onChange={(event) => setFields({ ...fields, [name]: event.target.value })} /> : <span className="block min-h-6">{fields[name] || "—"}</span>}</label>)}</div></section>)}<section><h3 className="hf-section-label mb-3">Bio</h3>{editing ? <textarea className="hf-input min-h-28" value={fields.bio ?? ""} onChange={(event) => setFields({ ...fields, bio: event.target.value })} /> : <p className="whitespace-pre-wrap leading-7">{fields.bio || "—"}</p>}</section>{editing ? <button className="hf-btn hf-btn-primary" type="submit">Save profile</button> : null}<p role="status" className="text-sm text-muted">{message}</p></form>;
}
