"use client";
import { useEffect, useState } from "react";
import type { QuestionBankEntry } from "@/core/applications/types";
export function QuestionBankEditor() {
  const [entries, setEntries] = useState<QuestionBankEntry[]>([]); const [editingId, setEditingId] = useState<string | null>(null); const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [aliases, setAliases] = useState(""); const [tags, setTags] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch("/api/question-bank"); const body = await response.json() as { data?: { entries?: QuestionBankEntry[] } }; setEntries(body.data?.entries ?? []); }
  useEffect(() => { void load(); }, []);
  async function save() { const split = (value: string) => value.split(",").map((item) => item.trim()).filter(Boolean); const response = await fetch("/api/question-bank", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editingId ?? undefined, canonicalQuestion: question, answer, aliases: split(aliases), tags: split(tags) }) }); if (!response.ok) { setMessage("Could not save entry."); return; } setEditingId(null); setQuestion(""); setAnswer(""); setAliases(""); setTags(""); setMessage("Saved."); await load(); }
  async function remove(id: string) { const response = await fetch(`/api/question-bank?id=${id}`, { method: "DELETE" }); setMessage(response.ok ? "Deleted." : "Could not delete entry."); await load(); }
  function edit(entry: QuestionBankEntry) { setEditingId(entry.id); setQuestion(entry.canonicalQuestion); setAnswer(entry.answer); setAliases(entry.aliases.join(", ")); setTags(entry.tags.join(", ")); }
  return <div className="space-y-5"><form className="hf-sheet-frame space-y-3 p-5" onSubmit={(event) => { event.preventDefault(); void save(); }}><label className="block text-sm">Canonical question<input className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" required value={question} onChange={(event) => setQuestion(event.target.value)} /></label><label className="block text-sm">Reusable answer<textarea className="hf-focus mt-1 min-h-28 w-full border border-border bg-inset px-3 py-2" required value={answer} onChange={(event) => setAnswer(event.target.value)} /></label><label className="block text-sm">Aliases, comma-separated<input className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={aliases} onChange={(event) => setAliases(event.target.value)} /></label><label className="block text-sm">Tags, comma-separated<input className="hf-focus mt-1 w-full border border-border bg-inset px-3 py-2" value={tags} onChange={(event) => setTags(event.target.value)} /></label><button className="hf-focus border border-accent-save px-4 py-2 text-sm">{editingId ? "Update answer" : "Save answer"}</button><p role="status" className="text-sm text-muted">{message}</p></form><ul className="space-y-3">{entries.map((entry) => <li key={entry.id} className="hf-sheet-frame p-4"><p className="font-medium">{entry.canonicalQuestion}</p><p className="mt-1 whitespace-pre-wrap text-sm text-muted">{entry.answer}</p><p className="mt-2 text-xs text-muted">Aliases: {entry.aliases.join(", ") || "—"} · Updated {new Date(entry.updatedAt).toLocaleDateString()}</p><div className="mt-3 flex gap-3"><button className="hf-focus text-sm underline" type="button" onClick={() => edit(entry)}>Edit</button><button className="hf-focus text-sm text-accent-danger underline" type="button" onClick={() => void remove(entry.id)}>Delete</button></div></li>)}</ul></div>;
}
