"use client";
import { useState } from "react";
import type { QuestionBankEntry } from "@/core/applications/types";

const UNSORTED = "Unsorted";
const folderOf = (entry: QuestionBankEntry) => entry.tags[0] || UNSORTED;
export function QuestionBankEditor({ initialEntries, initialFolders }: { initialEntries: QuestionBankEntry[]; initialFolders: string[] }) {
  const [entries, setEntries] = useState(initialEntries); const [folders, setFolders] = useState(initialFolders); const [folder, setFolder] = useState<string | null>(null); const [query, setQuery] = useState(""); const [editing, setEditing] = useState<QuestionBankEntry | null>(null); const [message, setMessage] = useState("");
  const visible = entries.filter((entry) => (!folder || folderOf(entry) === folder) && `${entry.canonicalQuestion} ${entry.aliases.join(" ")} ${entry.tags.join(" ")} ${entry.answer}`.toLowerCase().includes(query.toLowerCase()));
  async function foldersAction(body: Record<string, string>) { const response = await fetch("/api/question-bank", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json() as { data?: { folders?: string[] }; error?: { message?: string } }; if (!response.ok || !payload.data?.folders) { setMessage(payload.error?.message ?? "Could not update folders."); return; } setFolders(payload.data.folders); if (body.action === "rename_folder") setEntries((current) => current.map((entry) => entry.tags[0] === body.from ? { ...entry, tags: [body.to!, ...entry.tags.slice(1)] } : entry)); if (body.action === "delete_folder") setEntries((current) => current.map((entry) => entry.tags[0] === body.name ? { ...entry, tags: entry.tags.slice(1) } : entry)); setMessage("Folder updated."); }
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const split = (name: string) => String(form.get(name) ?? "").split(",").map((value) => value.trim()).filter(Boolean); const response = await fetch("/api/question-bank", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: editing?.id || undefined, canonicalQuestion: form.get("question"), answer: form.get("answer"), aliases: split("aliases"), tags: split("tags") }) }); const body = await response.json() as { data?: { entry?: QuestionBankEntry } }; if (!response.ok || !body.data?.entry) { setMessage("Could not save question."); return; } setEntries((current) => editing?.id ? current.map((entry) => entry.id === editing.id ? body.data!.entry! : entry) : [body.data!.entry!, ...current]); setEditing(null); setMessage("Question saved."); }
  async function removeEditing() { if (!editing?.id || !window.confirm(`Delete ${editing.canonicalQuestion}?`)) return; const response = await fetch(`/api/question-bank?id=${editing.id}`, { method: "DELETE" }); if (!response.ok) { setMessage("Could not delete question."); return; } setEntries((current) => current.filter((entry) => entry.id !== editing.id)); setEditing(null); setMessage("Question deleted."); }
  if (editing) return <form className="hf-sheet-frame mx-auto max-w-3xl space-y-4 p-5" onSubmit={(event) => void save(event)}><button type="button" className="hf-btn hf-btn-ghost" onClick={() => setEditing(null)}>← Question Bank</button><p className="hf-technical-label">{folderOf(editing)}</p><label className="block text-sm">Canonical question<input name="question" className="hf-input mt-1" required defaultValue={editing.canonicalQuestion} /></label><label className="block text-sm">Reusable answer<textarea name="answer" className="hf-input mt-1 min-h-40" required defaultValue={editing.answer} /></label><label className="block text-sm">Aliases, comma-separated<input name="aliases" className="hf-input mt-1" defaultValue={editing.aliases.join(", ")} /></label><label className="block text-sm">Tags (first tag is the folder)<input name="tags" className="hf-input mt-1" defaultValue={editing.tags.join(", ")} placeholder="Career, bio" /></label><div className="flex flex-wrap gap-2"><button className="hf-btn hf-btn-primary">Save</button>{editing.id ? <button type="button" className="hf-btn hf-btn-ghost text-accent-danger" onClick={() => void removeEditing()}>Delete</button> : null}</div></form>;
  return <div className="space-y-5"><div className="flex flex-wrap items-center gap-3"><input className="hf-input max-w-md" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search questions, aliases, tags, or answers" aria-label="Search question bank" /><button className="hf-btn hf-btn-primary" onClick={() => setEditing({ id: "", canonicalQuestion: "", answer: "", aliases: [], tags: [folder || UNSORTED], updatedAt: new Date().toISOString() })}>New question</button><button className="hf-btn hf-btn-ghost" onClick={() => { const name = window.prompt("Folder name"); if (name) void foldersAction({ action: "create_folder", name }); }}>New folder</button></div>{!folder && !query ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3">{folders.map((name) => <button key={name} className="hf-sheet-frame p-5 text-left hover:border-accent-save" onClick={() => setFolder(name)}><span className="text-3xl" aria-hidden>▣</span><strong className="mt-5 block">{name}</strong><span className="mt-1 block text-sm text-muted">{entries.filter((entry) => folderOf(entry) === name).length} questions</span></button>)}</div> : <><div className="flex flex-wrap gap-2"><button className="hf-btn hf-btn-ghost" onClick={() => { setFolder(null); setQuery(""); }}>← All folders</button>{folder ? <><button className="hf-btn hf-btn-ghost" onClick={() => { const to = window.prompt("Rename folder", folder); if (to && to !== folder) void foldersAction({ action: "rename_folder", from: folder, to }); }}>Rename folder</button><button className="hf-btn hf-btn-ghost text-accent-danger" onClick={() => { if (window.confirm(`Delete ${folder}? Questions will move to Unsorted.`)) { void foldersAction({ action: "delete_folder", name: folder }); setFolder(null); } }}>Delete folder</button></> : null}</div><div className="overflow-x-auto border-y border-border"><table className="w-full text-left text-sm"><thead className="text-xs text-muted"><tr><th className="p-3">Question</th><th className="p-3">Tags</th><th className="p-3">Updated</th></tr></thead><tbody>{visible.map((entry) => <tr key={entry.id} className="border-t border-border hover:bg-inset"><td className="p-3"><button className="hf-focus text-left font-medium" onClick={() => setEditing(entry)}>{entry.canonicalQuestion}</button></td><td className="p-3 text-muted">{entry.tags.join(", ") || "—"}</td><td className="p-3 text-muted">{new Date(entry.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div></>}<p role="status" className="text-sm text-muted">{message}</p></div>;
}
