-- Opportunity application vertical slice. Existing candidate rows remain hackathons.
alter table candidates add column if not exists opportunity_type text not null default 'hackathon' check (opportunity_type in ('hackathon','tech_event','conference','fellowship','pitch_competition','accelerator','startup_program','competition','other'));
alter table candidates add column if not exists organizer text;
alter table candidates add column if not exists application_opens_at timestamptz;
alter table candidates add column if not exists cost text;
alter table candidates add column if not exists travel_support text;

create table if not exists user_profiles (user_id uuid primary key, fields jsonb not null default '{}', updated_at timestamptz not null default now());
create table if not exists question_bank (id uuid primary key default gen_random_uuid(), user_id uuid not null, canonical_question text not null, answer text not null, aliases text[] not null default '{}', tags text[] not null default '{}', updated_at timestamptz not null default now());
create table if not exists applications (id uuid primary key default gen_random_uuid(), candidate_id uuid not null references candidates(id) on delete cascade, application_url text not null, status text not null default 'not_started' check (status in ('not_started','scheduled','drafting','needs_input','ready_for_review','approved','submitting','submitted','failed')), draft_version integer not null default 1, approved_draft_version integer, approved_at timestamptz, approved_by uuid, submitted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists application_questions (id uuid primary key default gen_random_uuid(), application_id uuid not null references applications(id) on delete cascade, question text not null, field_type text not null, required boolean not null default false, answer text, answer_source text not null default 'unresolved' check (answer_source in ('profile','question_bank','ai','user','unresolved')), needs_user_input boolean not null default false, form_selector text, options jsonb not null default '[]', max_length integer, position integer not null default 0, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table if not exists notifications (id uuid primary key default gen_random_uuid(), user_id uuid, type text not null check (type in ('APPLICATION_OPEN','APPLICATION_NEEDS_INPUT','APPLICATION_READY_FOR_REVIEW','DEADLINE_SOON','SUBMISSION_FAILED')), candidate_id uuid references candidates(id) on delete cascade, application_id uuid references applications(id) on delete cascade, title text not null, body text not null, action_url text, sent_at timestamptz not null default now(), unique (candidate_id, application_id, type));
create index if not exists idx_applications_status on applications(status);
create index if not exists idx_candidates_application_schedule on candidates(application_opens_at, deadline);
